### ISSUE TITLE
train.pkl of CUB dataset

### ISSUE THREAD

**Issue by optimus20** [xmed-lab/ECBM#1]
excuse me, I cannot find train.pkl of CUB dataset, how do you dule with CUB datasets?

**Comment by Thea-Hsu** [comment]
Hello,

Thank you for reaching out. We used the original CUB dataset. You can download it from [here](https://data.caltech.edu/records/65de6-vp158). After downloading, please follow the pre-processing instructions provided in the CBMs [README](https://github.com/yewsiang/ConceptBottleneck/blob/master/CUB/README.md) file to obtain the train.pkl file.
